### PR TITLE
Patched directory-1.3.1.0: avoid the use of tryIOError in createDirectoryIfMissing

### PR DESCRIPTION
**Pull request by jneira**
* As commented in https://github.com/typelead/eta/issues/689, code catching IOErrors doesn't work correctly
* To make `tryIOError` works (and `createDirectoryIfMissing`), we should change the mapping between java exceptions and haskell exceptions to take in account the possibles types of IO errors
* As a temporary workaround we've patched directory to avoid the use of `tryIOError` in `createDirectoryIfMissing`

### CODE REVIEW

**Comment by rahulmutt** [comment]
@jneira Thanks for the patch! Unfortunately, I am not able to see the contents to give a review - GitHub says that it's a binary file. What command did you use to generate the patch?

**Comment by jneira** [comment]
mmm, `git format-patch HEAD~ --stdout > directory-1.3.1.0.patch` as always
i recently upgrade git for windows:
```
PS C:\Users\Javier\dev\lang\eta\eta-hackage> git --version
git version 2.16.2.windows.1
```

**Comment by jneira** [comment]
@rahulmutt i've repeated the steps and the file continue being binary :-/
The last try was: `git format-patch HEAD~ --ignore-cr-at-eol --stdout > directory-1.3.1.0.patch`
With that the stats are:
```
 System/Directory.hs                  | 785 ++++++++++-------------------------
 System/Directory/Internal.hs         |  35 +-
 System/Directory/Internal/Config.hs  |   6 +-
 System/Directory/Internal/Prelude.hs |   6 +-
 directory.cabal                      |  17 +-
 java/Utils.java                      | 135 ++++++
 6 files changed, 381 insertions(+), 603 deletions(-)
 create mode 100644 java/Utils.java
```

**Comment by rahulmutt** [comment]
@jneira Ok I'll merge it in then since you've most likely done the correct fix. If there's any problem, I'll revert.

**Pull request merged**
