### PR TITLE
Patched microaeson-0.1.0.0

### PR DESCRIPTION
**Pull request by jneira**
To make HSYaml-2.0 work

### CODE REVIEW

**Comment by rahulmutt** [comment]
As discussed on Gitter, can you see if you can add a `build-tool-depends` to cut down this patch?

**Comment by jneira** [comment]
Mmm, i've tested it removing the global alex executable and with and without `build-tools` and `build-tool-depends`, both with and without deps bounds and it always asks for alex:
```
etlas.exe: The program 'alex' is required but it could not be found.
```

**Comment by jneira** [comment]
Mmm i start to wonder if it is a windows specific bug: i have alex in the store dir but in its bin dir there is the `alex.cmd` generated script for windows. When i try to run it with etlas it doesnt find the executable:
```
>etlas run alex -- --version
Up to date
etlas: Unknown executable alex in package
alex-3.2.4-0a3edf06fccf11618d5bdac1ec38e9eeffa31933
```

I guess in linux it is able to run the wrapper script over the java call but it can't in windows..

**Comment by jneira** [comment]
Uh, ignore the previous comment, i wipe out the alex folder in the store and after rebuild etlas is able to execute it, weird... the new folder is apparently equal to removed one

**Comment by jneira** [comment]
If i set in etlas global config the exact path of alex `.cmd` script it can execute it when building the package:

```
program-locations
  alex-location: \path\to\etlas\store\alex-3.2.4-hash\bin\alex.cmd
```
so i think `programFindLocation` or `findProgramOnSearchPath` are not able to find the `.cmd` script in windows.
As there is a workaround and i think in linux/macos it will work i am gonna change the patch to restore the `.x` file

**Comment by jneira** [comment]
Another definitive test: if i remove the hardcoded location in etlas config and put the `alex.exe` in `\path\to\etlas\store\alex-3.2.4-hash\bin` etlas execute them building the package.

And if we have another alex in global `PATH` etlas picks up it.

**Comment by jneira** [comment]
Closing cause the package can be built patching aeson-1.3.1.1 to build tests

**Pull request closed without merging**
